name: Build CZSC Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # 4. 打包为可执行文件
    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    # 5. 保存打包结果到构建产物
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: czsc-executable
        path: dist/
